version: '3'
services:
  Master: 
    image: gyb333/bigdata 
    container_name: Master
    hostname: Master
    ports:
       - "9000:9000"
       - "50070:50070"
       - "8088:8088"
       - "8486:8485"
       - "10020:10020"  
       - "19888:19888"
       - "9001:9001"
       - "50030:50030"
       - "10000:10000"
       - "16010:16010"
       - "16030:16030"
       - "8080:8080"  
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
        reservations:
          cpus: '0.1'
          memory: 256M
    extra_hosts:
      - "Master:172.23.0.2"
      - "Second:172.23.0.3"
      - "Slave:172.23.0.4"
      - "Hadoop:192.168.56.100"
    networks:
       default:
         ipv4_address: 172.23.0.2
  Second: 
    image: gyb333/bigdata
    container_name: Second
    hostname: Second
    depends_on:
      - Master
    ports:
      - "9010:9000"
      - "51070:50070"
      - "8188:8088"
      - "8487:8485"

    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    extra_hosts:
      - "Master:172.23.0.2"
      - "Second:172.23.0.3"
      - "Slave:172.23.0.4"
      - "Hadoop:192.168.56.100"
    networks:
       default:
         ipv4_address: 172.23.0.3
  Slave: 
    image: gyb333/bigdata
    container_name: Slave
    hostname: Slave
    depends_on:
      - Second
    ports:
      - "8488:8485"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    extra_hosts:
      - "Master:172.23.0.2"
      - "Second:172.23.0.3"
      - "Slave:172.23.0.4"
      - "Hadoop:192.168.56.100"
    networks:
       default:
         ipv4_address: 172.23.0.4
networks:
  default:
    external:
      name: network
 
