version: '3.7'

services:
  kafka-node1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka-node1
    container_name: kafka-node1
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-node1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zkMaster:2181,zkSecond:2181,zkSlave:2181
    volumes:
    - ./kafka-node1/logs:/kafka
    external_links:
    - zkMaster
    - zkSecond
    - zkSlave
    networks:
      network:
        ipv4_address: 172.23.0.31

  kafka-node2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka-node2
    container_name: kafka-node2
    ports:
    - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-node2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zkMaster:2181,zkSecond:2181,zkSlave:2181
    volumes:
    - ./kafka-node2/logs:/kafka
    external_links:
    - zkMaster
    - zkSecond
    - zkSlave
    networks:
      network:
        ipv4_address: 172.23.0.32

  kafka-node3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka-node3
    container_name: kafka-node3
    ports:
    - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-node3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zkMaster:2181,zkSecond:2181,zkSlave:2181
    volumes:
    - ./kafka-node3/logs:/kafka
    external_links:
    - zkMaster
    - zkSecond
    - zkSlave
    networks:
      network:
        ipv4_address: 172.23.0.33

networks:
  network:
    external:
      name: network