version: '3.1'
services:
    zkMaster:
        image: zookeeper
        restart: always
        hostname: zkMaster
        container_name: zkMaster
        ports:
            - "2181:2181"
 #       network_mode: "bridge"
        volumes:
            - /usr/local/docker/zookeeper/zkMaster/data:/data
            - /usr/local/docker/zookeeper/zkMaster/datalog:/datalog
            - /usr/local/docker/zookeeper/zkMaster/conf:/conf
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zkMaster:2888:3888 server.2=zkSecond:2888:3888 server.3=zkSlave:2888:3888 clientPort=2181
        networks:
          default:
            ipv4_address: 172.23.0.11
    zkSecond:
        image: zookeeper
        restart: always
        hostname: zkSecond
        container_name: zkSecond
        ports:
            - "2182:2181"
  #      network_mode: "bridge"
        volumes:
            - /usr/local/docker/zookeeper/zkSecond/data:/data
            - /usr/local/docker/zookeeper/zkSecond/datalog:/datalog
            - /usr/local/docker/zookeeper/zkSecond/conf:/conf
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zkMaster:2888:3888 server.2=zkSecond:2888:3888 server.3=zkSlave:2888:3888 clientPort=2181
        networks:
          default:
            ipv4_address: 172.23.0.12
    zkSlave:
        image: zookeeper
        restart: always
        hostname: zkSlave
        container_name: zkSlave
        ports:
            - "2183:2181"
   #     network_mode: "bridge"
        volumes:
            - /usr/local/docker/zookeeper/zkSlave/data:/data
            - /usr/local/docker/zookeeper/zkSlave/datalog:/datalog
            - /usr/local/docker/zookeeper/zkSlave/conf:/conf
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zkMaster:2888:3888 server.2=zkSecond:2888:3888 server.3=zkSlave:2888:3888 clientPort=2181
        networks:
          default:
            ipv4_address: 172.23.0.13
networks:
  default:
    external:
      name: network
